// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-o4OUjHi-KgT4BJXZ3nrmULQ9AXU3oVA',
    appId: '1:218479524770:web:7434ec2f847fb16ca890fb',
    messagingSenderId: '218479524770',
    projectId: 'flutter-coding-challenge-1888b',
    authDomain: 'flutter-coding-challenge-1888b.firebaseapp.com',
    storageBucket: 'flutter-coding-challenge-1888b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASxl_cY-znrlR_psuEFN1hHeZvew_GS54',
    appId: '1:218479524770:android:62f0f45962b3f07ba890fb',
    messagingSenderId: '218479524770',
    projectId: 'flutter-coding-challenge-1888b',
    storageBucket: 'flutter-coding-challenge-1888b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQyjDHM7CATOpukWsQp5A2BDEPRp7b9mo',
    appId: '1:218479524770:ios:51fb367db8331306a890fb',
    messagingSenderId: '218479524770',
    projectId: 'flutter-coding-challenge-1888b',
    storageBucket: 'flutter-coding-challenge-1888b.appspot.com',
    iosBundleId: 'com.example.codingChallenge',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQyjDHM7CATOpukWsQp5A2BDEPRp7b9mo',
    appId: '1:218479524770:ios:51fb367db8331306a890fb',
    messagingSenderId: '218479524770',
    projectId: 'flutter-coding-challenge-1888b',
    storageBucket: 'flutter-coding-challenge-1888b.appspot.com',
    iosBundleId: 'com.example.codingChallenge',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-o4OUjHi-KgT4BJXZ3nrmULQ9AXU3oVA',
    appId: '1:218479524770:web:e4022ab403ee0635a890fb',
    messagingSenderId: '218479524770',
    projectId: 'flutter-coding-challenge-1888b',
    authDomain: 'flutter-coding-challenge-1888b.firebaseapp.com',
    storageBucket: 'flutter-coding-challenge-1888b.appspot.com',
  );
}
